import {
  WBreadcrumb,
  WConfigProvider,
  WContainer,
  WDictTag,
  WFileUpload,
  WFormContainer,
  WFullScreen,
  WHamburger,
  WHeaderSearch,
  WImagePreview,
  WImageUpload,
  WPagination,
  WRightToolbar,
  WSearchContainer,
  WSizeSelect,
  WSvgIcon,
  WTableContainer,
  WTopNav,
  WTreeSelect,
  // 以下组件不会全局安装
  // WCronTab,
  WLayout,
  WInnerLink,
} from '@way-ui/components';

export default [
  WBreadcrumb,
  WConfigProvider,
  WContainer,
  WDictTag,
  WFileUpload,
  WFormContainer,
  WFullScreen,
  WHamburger,
  WHeaderSearch,
  WImagePreview,
  WImageUpload,
  WPagination,
  WRightToolbar,
  WSearchContainer,
  WSizeSelect,
  WSvgIcon,
  WTableContainer,
  WTopNav,
  WTreeSelect,
];

export {
  // WCronTab,
  WLayout,
  WInnerLink,
};
