import {
  WBreadcrumb,
  WConfigProvider,
  WContainer,
  WDatePicker,
  WDateRangePicker,
  WDescriptions,
  WDescriptionsItem,
  WDictTag,
  WFileUpload,
  WFormContainer,
  WFormHeader,
  WFormItemGroup,
  WFullScreen,
  WHamburger,
  WHeaderSearch,
  WImagePreview,
  WImageUpload,
  WLayout,
  WLowCodeRenderer,
  WPagination,
  WRightToolbar,
  WSearchContainer,
  WSizeSelect,
  WSvgIcon,
  WTableContainer,
  WTopNav,
  WTreeSelect,
  // 计划免疫
  WLayoutJm,
  WSearchContainerJm,
} from '@way-ui/components';

export default [
  WBreadcrumb,
  WConfigProvider,
  WContainer,
  WDatePicker,
  WDateRangePicker,
  WDescriptions,
  WDescriptionsItem,
  WDictTag,
  WFileUpload,
  WFormContainer,
  WFormHeader,
  WFormItemGroup,
  WFullScreen,
  WHamburger,
  WHeaderSearch,
  WImagePreview,
  WImageUpload,
  WLayout,
  WLowCodeRenderer,
  WPagination,
  WRightToolbar,
  WSearchContainer,
  WSizeSelect,
  WSvgIcon,
  WTableContainer,
  WTopNav,
  WTreeSelect,
  // 计划免疫
  WLayoutJm,
  WSearchContainerJm,
];
